firstnumber = input("First number is: ")
secondnumber = input("Second number is: ")
thirdnumber = input("Third number is: ")
total = int(firstnumber) + int(secondnumber) + int(thirdnumber)
print (total)